// Generated by CoffeeScript 1.3.3
(function() {
  var findSync;

  findSync = require("../../../utils/files").findSync;

  exports.initialize = function(config) {
    var d, dirs, sources, _i, _len;
    dirs = ['src/async', 'src/core', 'src/utils'];
    sources = [];
    for (_i = 0, _len = dirs.length; _i < _len; _i++) {
      d = dirs[_i];
      sources = sources.concat(findSync('coffee', d));
    }
    return config.docco = {
      paths: {
        sources: sources
      }
    };
  };

}).call(this);
