// Generated by CoffeeScript 1.3.3
(function() {

  exports.initialize = function(config) {
    return config.docco = {
      paths: {
        tmp: '.tmp/docco',
        demos: 'config/demos',
        sources: []
      }
    };
  };

}).call(this);
