// Generated by CoffeeScript 1.3.3
(function() {
  var findSync;

  findSync = require("../../../utils/files").findSync;

  exports.initialize = function(config) {
    var sources;
    sources = [];
    sources = sources.concat(findSync('coffee', 'src/core'));
    sources = sources.concat(findSync('coffee', 'src/utils'));
    return config.docco = {
      paths: {
        tmp: '.tmp/docco',
        demos: 'config/demos',
        sources: sources
      }
    };
  };

}).call(this);
