// Generated by CoffeeScript 1.3.3
(function() {
  var Neat, error, green, info, neatTask, red, rm, run, _, _ref, _ref1;

  Neat = require('../neat');

  _ref = require('../utils/commands'), run = _ref.run, neatTask = _ref.neatTask;

  _ref1 = require('../utils/logs'), error = _ref1.error, info = _ref1.info, green = _ref1.green, red = _ref1.red;

  rm = require('../utils/files').rm;

  _ = Neat.i18n.getHelper();

  exports.compile = neatTask({
    name: 'compile',
    description: _('neat.tasks.compile.description'),
    action: function(callback) {
      return Neat.beforeCompilation.dispatch(function() {
        var args, coffee, lib, _ref2;
        _ref2 = Neat.config.tasks.compile, coffee = _ref2.coffee, args = _ref2.args, lib = _ref2.lib;
        return rm(lib, function(err) {
          return run(coffee, args, function(status) {
            if (status === 0) {
              info(green(_('neat.tasks.compile.compilation_done')));
            } else {
              error(red(_('neat.tasks.compile.compilation_failed')));
            }
            return Neat.afterCompilation.dispatch(function() {
              return typeof callback === "function" ? callback(status) : void 0;
            });
          });
        });
      });
    }
  });

}).call(this);
