// Generated by CoffeeScript 1.3.3
(function() {
  var COFFEE, Neat, error, green, info, neatTask, red, run, _ref, _ref1;

  Neat = require('../neat');

  _ref = require('../utils/commands'), run = _ref.run, neatTask = _ref.neatTask;

  _ref1 = require('../utils/logs'), error = _ref1.error, info = _ref1.info, green = _ref1.green, red = _ref1.red;

  COFFEE = "" + Neat.neatRoot + "/node_modules/.bin/coffee";

  exports.compile = neatTask({
    name: 'compile',
    description: 'Compiles the sources',
    action: function(callback) {
      var lib, src;
      lib = "" + Neat.root + "/" + Neat.config.tasks.compile.compilationDirectory;
      src = "" + Neat.root + "/" + Neat.config.tasks.compile.sourceDirectory;
      return run(COFFEE, ['-c', '-o', lib, src], function(status) {
        if (status === 0) {
          info(green('Compilation done'));
        } else {
          error(red('Compilation failed'));
        }
        return typeof callback === "function" ? callback(status) : void 0;
      });
    }
  });

}).call(this);
