// Generated by CoffeeScript 1.3.3
(function() {
  var Neat, error, green, info, neatTask, puts, red, run, _ref, _ref1;

  Neat = require('../neat');

  _ref = require('../utils/commands'), run = _ref.run, neatTask = _ref.neatTask;

  _ref1 = require('../utils/logs'), error = _ref1.error, info = _ref1.info, green = _ref1.green, red = _ref1.red, puts = _ref1.puts;

  exports.deploy = neatTask({
    name: 'deploy',
    description: 'Installs the module globally through npm',
    action: function(callback) {
      return Neat.task('compile')(function(status) {
        if (status === 0) {
          return run('npm', ['install', '-g'], function(status) {
            if (status === 0) {
              info(green('Neat installed'));
            } else {
              error(red('Something went wrong during installation'));
            }
            return typeof callback === "function" ? callback(status) : void 0;
          });
        } else {
          puts('Compilation have failed, please fix it before\
              deploying the module again'.squeeze());
          return typeof callback === "function" ? callback(status) : void 0;
        }
      });
    }
  });

}).call(this);
