// Generated by CoffeeScript 1.3.3
(function() {
  var Neat, error, green, info, neatTask, path, puts, queue, red, yellow, _ref;

  path = require('path');

  Neat = require('../neat');

  queue = require('../async').queue;

  neatTask = require('../utils/commands').neatTask;

  _ref = require('../utils/logs'), error = _ref.error, info = _ref.info, green = _ref.green, red = _ref.red, yellow = _ref.yellow, puts = _ref.puts;

  exports.test = neatTask({
    name: 'test',
    description: 'Tests the sources',
    action: function(callback) {
      return Neat.task('compile')(function(status) {
        var actions, f, k;
        if (status === 0) {
          actions = (function() {
            var _ref1, _results;
            _ref1 = Neat.env.engines.tests;
            _results = [];
            for (k in _ref1) {
              f = _ref1[k];
              _results.push(f);
            }
            return _results;
          })();
          return queue(actions, function() {
            return typeof callback === "function" ? callback() : void 0;
          });
        } else {
          puts;

          return typeof callback === "function" ? callback() : void 0;
        }
      });
    }
  });

}).call(this);
