// Generated by CoffeeScript 1.3.3
(function() {
  var Neat, beforeTests, error, functional, green, index, info, namespace, neatTask, path, puts, queue, red, runTests, test, unit, yellow, _ref;

  path = require('path');

  Neat = require('../neat');

  queue = require('../async').queue;

  neatTask = require('../utils/commands').neatTask;

  namespace = require('../utils/exports').namespace;

  _ref = require('../utils/logs'), error = _ref.error, info = _ref.info, green = _ref.green, red = _ref.red, yellow = _ref.yellow, puts = _ref.puts;

  test = function(k, f, n, d) {
    return function(callback) {
      return f(n, d, function() {
        return typeof callback === "function" ? callback() : void 0;
      });
    };
  };

  beforeTests = function(test) {
    return function(callback) {
      return Neat.task('compile')(function(status) {
        if (status === 0) {
          return test(callback);
        } else {
          return typeof callback === "function" ? callback() : void 0;
        }
      });
    };
  };

  runTests = function(name, dir) {
    return function(callback) {
      var actions, f, k;
      actions = (function() {
        var _ref1, _results;
        _ref1 = Neat.env.engines.tests;
        _results = [];
        for (k in _ref1) {
          f = _ref1[k];
          _results.push(test(k, f, name, dir));
        }
        return _results;
      })();
      return queue(actions, function() {
        return typeof callback === "function" ? callback() : void 0;
      });
    };
  };

  index = neatTask({
    name: 'test',
    description: 'Run all tests',
    environment: 'test',
    action: beforeTests(function(callback) {
      return runTests('unit', 'test/units')(function(status) {
        return runTests('functional', 'test/functionals')(function(status) {
          info(green('All tests complete'));
          return typeof callback === "function" ? callback() : void 0;
        });
      });
    })
  });

  unit = neatTask({
    name: 'test:unit',
    description: 'Run unit tests',
    environment: 'test',
    action: beforeTests(function(callback) {
      return runTests('unit', 'test/units')(function() {
        info(green('All tests complete'));
        return typeof callback === "function" ? callback() : void 0;
      });
    })
  });

  functional = neatTask({
    name: 'test:functional',
    description: 'Run functional tests',
    environment: 'test',
    action: beforeTests(function(callback) {
      return runTests('functional', 'test/functionals')(function() {
        info(green('All tests complete'));
        return typeof callback === "function" ? callback() : void 0;
      });
    })
  });

  module.exports = namespace('test', {
    index: index,
    unit: unit,
    functional: functional
  });

}).call(this);
