// Generated by CoffeeScript 1.3.3
(function() {
  var op;

  op = require('../../../tasks/package/operators');

  module.exports = function(config) {
    return config.tasks["package"].merge({
      operatorsMap: {
        'annotate:class': op.annotateClass,
        'annotate:file': op.annotateFile,
        'join': op.join,
        'compile': op.compile,
        'uglify': op.uglify,
        'create:directory': op.createDirectory,
        'strip:requires': op.stripRequires,
        'exports:package': op.exportsToPackage,
        'saveToFile': op.saveToFile
      }
    });
  };

}).call(this);
