// Generated by CoffeeScript 1.3.3
(function() {
  var parallel, queue;

  parallel = function(fns, callback) {
    var cb, count, fn, _i, _len, _results;
    count = 0;
    cb = function() {
      count += 1;
      if (count === fns.length) {
        return typeof callback === "function" ? callback() : void 0;
      }
    };
    if (fns.empty()) {
      return callback();
    } else {
      _results = [];
      for (_i = 0, _len = fns.length; _i < _len; _i++) {
        fn = fns[_i];
        _results.push(fn(cb));
      }
      return _results;
    }
  };

  queue = function(fns, callback) {
    var next;
    next = function() {
      if (fns.empty()) {
        return callback();
      } else {
        return fns.shift()(next);
      }
    };
    return next();
  };

  module.exports = {
    queue: queue,
    parallel: parallel
  };

}).call(this);
