// Generated by CoffeeScript 1.3.3
(function() {
  var Parallel,
    __slice = [].slice;

  Parallel = (function() {

    function Parallel() {
      var commands;
      commands = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      this.commands = commands.flatten();
    }

    Parallel.prototype.run = function(callback) {
      var command, f, _i, _len, _ref, _results,
        _this = this;
      this.counter = 0;
      f = function() {
        _this.counter += 1;
        if (_this.counter === _this.commands.length) {
          return typeof callback === "function" ? callback() : void 0;
        }
      };
      _ref = this.commands;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        command = _ref[_i];
        _results.push(command(f));
      }
      return _results;
    };

    return Parallel;

  })();

  module.exports = Parallel;

}).call(this);
