// Generated by CoffeeScript 1.3.3
(function() {
  var Queue,
    __slice = [].slice;

  Queue = (function() {

    function Queue() {
      var commands;
      commands = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      this.commands = commands.flatten();
      this.iterator = 0;
    }

    Queue.prototype.run = function(callback) {
      var _this = this;
      if (this.iterator < this.commands.length) {
        this.commands[this.iterator](function() {
          return _this.run(callback);
        });
        return this.iterator += 1;
      } else {
        return typeof callback === "function" ? callback() : void 0;
      }
    };

    return Queue;

  })();

  module.exports = Queue;

}).call(this);
