// Generated by CoffeeScript 1.3.3
(function() {
  var CLICommand, Neat, cmdMap, commandTrigger, commands, core, error, fs, g, help, k, missing, pr, print, puts, register, resolve, spawn, _ref,
    __slice = [].slice;

  fs = require('fs');

  pr = require('commander');

  spawn = require('child_process').spawn;

  resolve = require('path').resolve;

  core = require('./core');

  _ref = require("./utils/logs"), puts = _ref.puts, print = _ref.print, error = _ref.error, missing = _ref.missing;

  Neat = require('./neat');

  CLICommand = require('./core/interfaces/cli_command');

  commands = require("./commands");

  commandTrigger = function(c) {
    return function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (c.environment != null) {
        Neat.defaultEnvironment = c.environment;
      }
      Neat.initEnvironment();
      Neat.beforeCommand.dispatch();
      return c.apply(null, args.concat(function() {
        return Neat.afterCommand.dispatch();
      }));
    };
  };

  cmdMap = {};

  register = function(k, c) {
    var alias, _i, _len, _ref1, _results;
    if (!c.quacksLike(CLICommand)) {
      return error("" + ("Can't register command " + k).red + "\n\nA command must be function with an aliases.");
    }
    _ref1 = c.aliases;
    _results = [];
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      alias = _ref1[_i];
      pr.command(alias).description(c.description).action(commandTrigger(c));
      _results.push(cmdMap[k] = c);
    }
    return _results;
  };

  pr.version(Neat.meta.version);

  for (k in commands) {
    g = commands[k];
    register(k, g(pr, cmdMap));
  }

  pr.command("*").action(function(command) {
    return error("" + (missing("Command " + command)) + "\n\nTry `neat help` for a list of the available commands.");
  });

  pr.parse(process.argv);

  help = cmdMap.help;

  if (pr.args.length === 0 && (help != null)) {
    commandTrigger(help)();
  }

}).call(this);
