// Generated by CoffeeScript 1.3.3
(function() {
  var Neat, cmdMap, commands, core, error, fs, g, help, k, missing, pr, print, puts, register, resolve, spawn, _ref;

  fs = require('fs');

  pr = require('commander');

  spawn = require('child_process').spawn;

  resolve = require('path').resolve;

  core = require(resolve(__dirname, 'core'));

  _ref = require(resolve(__dirname, "utils/logs")), puts = _ref.puts, print = _ref.print, error = _ref.error, missing = _ref.missing;

  Neat = require(resolve(__dirname, 'neat'));

  Neat.initEnvironment();

  Neat.initLogging();

  commands = require(resolve(__dirname, "commands"));

  cmdMap = {};

  register = function(k, c) {
    var alias, _i, _len, _ref1, _results;
    if (c.aliases == null) {
      return print(("Can't register command " + k + " due to missing aliases\n").red);
    }
    _ref1 = c.aliases;
    _results = [];
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      alias = _ref1[_i];
      pr.command(alias).description(c.description).action(c);
      _results.push(cmdMap[k] = c);
    }
    return _results;
  };

  pr.version(Neat.meta.version);

  for (k in commands) {
    g = commands[k];
    register(k, g(pr, cmdMap));
  }

  pr.command("*").action(function(command) {
    return puts("" + (missing("Command " + command)) + "\n\nTry `neat help` for a list of the available commands.");
  });

  pr.parse(process.argv);

  help = cmdMap.help;

  if (pr.args.length === 0 && (help != null)) {
    help();
  }

}).call(this);
