// Generated by CoffeeScript 1.3.3
(function() {
  var Neat, resolve;

  resolve = require('path').resolve;

  Neat = require('./neat');

  module.exports = {
    Neat: Neat,
    async: require(resolve(Neat.neatRoot, 'lib/async')),
    core: require(resolve(Neat.neatRoot, 'lib/core')),
    utils: require(resolve(Neat.neatRoot, 'lib/utils'))
  };

}).call(this);
