// Generated by CoffeeScript 1.3.3
(function() {
  var Neat, resolve, utils;

  resolve = require('path').resolve;

  Neat = require('./env').Neat;

  utils = resolve(Neat.neatRoot, 'lib/utils');

  module.exports = {
    Neat: Neat,
    utils: {
      commands: require(resolve(utils, 'commands')),
      cup: require(resolve(utils, 'cup')),
      exports: require(resolve(utils, 'exports')),
      files: require(resolve(utils, 'files')),
      logs: require(resolve(utils, 'logs')),
      templates: require(resolve(utils, 'templates'))
    }
  };

}).call(this);
