navigation:
  Home:
    href: 'index.html'
    class: 'icon-home'
  Pages:
    href: 'pages_index.html'
    class: 'icon-file-alt'
  Documentation:
    href: 'docs/src_index.html'
    class: 'icon-sitemap'
  GitHub:
    href: 'http://github.com/abe33/neat'
    class: 'icon-github'

templates:
  header: 'templates/pages/header.html.hamlc'
  footer: 'templates/pages/footer.html.hamlc'
  layout: 'templates/pages/layout.html.hamlc'
