// Generated by CoffeeScript 1.3.1
(function() {

  Number.prototype.ago = function() {
    return new Date(new Date().getTime() - this.valueOf());
  };

  Number.prototype.days = function() {
    return this.hours() * 24;
  };

  Number.prototype.even = function() {
    return this.valueOf() % 2 === 0;
  };

  Number.prototype.fromNow = function() {
    return new Date(new Date().getTime() + this.valueOf());
  };

  Number.prototype.hours = function() {
    return this.minutes() * 60;
  };

  Number.later = function() {
    return this.fromNow();
  };

  Number.prototype.minutes = function() {
    return this.seconds() * 60;
  };

  Number.prototype.odd = function() {
    return this.valueOf() % 2 === 1;
  };

  Number.prototype.seconds = function() {
    return this.valueOf() * 1000;
  };

  Number.prototype.times = function(target) {
    var i, o, _i, _ref;
    if (typeof target === "function") {
      return (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = this.valueOf() - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push(target(i));
        }
        return _results;
      }).call(this);
    }
    o = target;
    for (i = _i = 1, _ref = this.valueOf() - 1; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
      if (target.concat != null) {
        o = o.concat(target);
      } else {
        o += target;
      }
    }
    return o;
  };

  Number.prototype.to = function(end, callback) {
    var i, _i, _ref, _results;
    _results = [];
    for (i = _i = _ref = this.valueOf(); _ref <= end ? _i <= end : _i >= end; i = _ref <= end ? ++_i : --_i) {
      _results.push(callback(i));
    }
    return _results;
  };

  Number.prototype.weeks = function() {
    return this.days() * 7;
  };

}).call(this);
