// Generated by CoffeeScript 1.3.3
(function() {
  var Neat, aliases, decorate, describe, environment, error, help, print, puts, resolve, run, spawn, usages, _ref,
    __slice = [].slice;

  spawn = require('child_process').spawn;

  resolve = require('path').resolve;

  _ref = require('./logs'), puts = _ref.puts, print = _ref.print, error = _ref.error;

  Neat = require('../neat');

  decorate = function(target, property, value) {
    target[property] = value;
    return target;
  };

  usages = function() {
    var target, usages, _i;
    usages = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), target = arguments[_i++];
    return decorate(target, 'usages', usages);
  };

  aliases = function() {
    var aliases, target, _i;
    aliases = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), target = arguments[_i++];
    return decorate(target, 'aliases', aliases);
  };

  describe = function(description, target) {
    return decorate(target, 'description', description);
  };

  help = function(help, target) {
    return decorate(target, 'help', help);
  };

  environment = function(env, target) {
    return decorate(target, 'environment', env);
  };

  run = function(command, options, callback) {
    var exe;
    exe = spawn(command, options);
    exe.stdout.on('data', function(data) {
      return print(data.toString());
    });
    exe.stderr.on('data', function(data) {
      return print(error(data.toString()));
    });
    return exe.on('exit', function(status) {
      return typeof callback === "function" ? callback() : void 0;
    });
  };

  module.exports = {
    aliases: aliases,
    decorate: decorate,
    describe: describe,
    help: help,
    run: run,
    usages: usages,
    environment: environment
  };

}).call(this);
