// Generated by CoffeeScript 1.3.3
(function() {
  var compile, error, puts, read, resolve, spawn, _ref;

  resolve = require('path').resolve;

  spawn = require('child_process').spawn;

  compile = require('coffee-script').compile;

  _ref = require('./logs'), puts = _ref.puts, error = _ref.error;

  read = function(str) {
    try {
      return eval(compile("" + str, {
        bare: true
      }));
    } catch (e) {
      return null;
    }
  };

  module.exports = {
    read: read
  };

}).call(this);
