// Generated by CoffeeScript 1.3.1
(function() {
  var basename, combine, error, findSync, missing, namespace, puts, resolve, warn, _ref, _ref1;

  _ref = require('path'), resolve = _ref.resolve, basename = _ref.basename;

  _ref1 = require('./logs'), puts = _ref1.puts, error = _ref1.error, warn = _ref1.warn, missing = _ref1.missing;

  findSync = require("../utils/files").findSync;

  namespace = function(namespace, exports) {
    var k, packaged, v;
    packaged = {};
    if (exports["index"] != null) {
      packaged[namespace] = exports["index"];
    }
    for (k in exports) {
      v = exports[k];
      if (k !== "index") {
        packaged["" + namespace + ":" + k] = v;
      }
    }
    return packaged;
  };

  combine = function(filePattern, paths) {
    var file, files, k, packaged, required, s, v, _i, _len;
    files = findSync(filePattern, 'js', paths);
    packaged = {};
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      try {
        required = require(file);
        for (k in required) {
          v = required[k];
          packaged[k] = v;
        }
      } catch (e) {
        s = error("" + ("Broken file " + file).red + "\n\n" + e.stack);
        puts(s.red);
      }
    }
    return packaged;
  };

  module.exports = {
    namespace: namespace,
    combine: combine
  };

}).call(this);
