// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    commands: require('./commands'),
    cup: require('./cup'),
    exports: require('./exports'),
    files: require('./files'),
    logs: require('./logs'),
    templates: require('./templates')
  };

}).call(this);
