// Generated by CoffeeScript 1.3.3
(function() {
  var at, first, last, length, property;

  at = function(index, mapper) {
    if (index == null) {
      index = 0;
    }
    return function(el) {
      if (mapper != null) {
        return mapper(el != null ? el[index] : void 0);
      } else {
        return el != null ? el[index] : void 0;
      }
    };
  };

  first = function(mapper) {
    return function(el) {
      if (mapper != null) {
        return mapper(el != null ? typeof el.first === "function" ? el.first() : void 0 : void 0);
      } else {
        return el != null ? typeof el.first === "function" ? el.first() : void 0 : void 0;
      }
    };
  };

  last = function(mapper) {
    return function(el) {
      if (mapper != null) {
        return mapper(el != null ? typeof el.last === "function" ? el.last() : void 0 : void 0);
      } else {
        return el != null ? typeof el.last === "function" ? el.last() : void 0 : void 0;
      }
    };
  };

  length = function() {
    return function(el) {
      if (typeof (el != null ? el.length : void 0) === 'function') {
        return el != null ? el.length() : void 0;
      } else {
        return el != null ? el.length : void 0;
      }
    };
  };

  property = function(key, mapper) {
    return function(el) {
      if (mapper != null) {
        return mapper(el[key]);
      } else {
        return el[key];
      }
    };
  };

  module.exports = {
    at: at,
    first: first,
    last: last,
    length: length,
    property: property
  };

}).call(this);
