// Generated by CoffeeScript 1.3.3
(function() {
  var Neat, error, extname, findSiblingFile, findSiblingFileSync, fs, missing, puts, render, renderSync, _ref, _ref1;

  fs = require('fs');

  extname = require('path').extname;

  Neat = require('../neat');

  _ref = require("../utils/files"), findSiblingFile = _ref.findSiblingFile, findSiblingFileSync = _ref.findSiblingFileSync;

  _ref1 = require("../utils/logs"), puts = _ref1.puts, error = _ref1.error, missing = _ref1.missing;

  render = function(file, context, callback) {
    var _ref2;
    if (typeof context === 'function') {
      _ref2 = [{}, context], context = _ref2[0], callback = _ref2[1];
    }
    return findSiblingFile(file, Neat.paths, "templates", function(e, tplfile, a) {
      var ext;
      if (e != null) {
        return typeof callback === "function" ? callback(e) : void 0;
      }
      if (tplfile == null) {
        return typeof callback === "function" ? callback(new Error("" + (missing("Template for " + file)) + "\n\nExplored paths:\n" + (a.join("\n")))) : void 0;
      }
      puts("template found: " + tplfile.yellow);
      ext = extname(tplfile).slice(1);
      render = Neat.config.engines.templates[ext].render;
      if (render == null) {
        if (typeof callback === "function") {
          callback(new Error("" + (missing("" + ext + " template backend"))));
        }
      }
      puts("engine found for " + ext.cyan);
      return fs.readFile(tplfile, function(err, tpl) {
        if (err) {
          if (typeof callback === "function") {
            callback(new Error(error("Can't access " + tplfile.red + "\n\n" + err.stack)));
          }
        }
        return typeof callback === "function" ? callback(null, render(tpl.toString(), context)) : void 0;
      });
    });
  };

  renderSync = function(file, context) {
    var ext, paths, tpl, tplfile;
    paths = [];
    tplfile = findSiblingFileSync(file, Neat.paths, "templates", "*", paths);
    if (tplfile == null) {
      return typeof callback === "function" ? callback(new Error("" + (missing("Template for " + file)) + "\n\nExplored paths:\n" + (a.join("\n")))) : void 0;
    }
    puts("template found: " + tplfile.yellow);
    ext = extname(tplfile).slice(1);
    render = Neat.config.engines.templates[ext].render;
    if (render == null) {
      throw new Error("" + (missing("" + ext + " template backend")));
    }
    puts("engine found for " + ext.cyan);
    try {
      tpl = fs.readFileSync(tplfile);
    } catch (e) {
      e.message = error("Can't access " + tplfile.red + "\n" + e.message);
      throw e;
    }
    return render(tpl.toString(), context);
  };

  module.exports = {
    render: render,
    renderSync: renderSync
  };

}).call(this);
