// Generated by CoffeeScript 1.3.3
(function() {
  var DoccoFileProcessor, DoccoPreProcessor, Parallel, fs, highlight, parse, render, resolve, _ref;

  fs = require('fs');

  resolve = require('path').resolve;

  render = require('../../utils/templates').render;

  DoccoPreProcessor = require('./docco_pre_processor');

  Parallel = require('../../async/parallel');

  try {
    _ref = require('docco'), parse = _ref.parse, highlight = _ref.highlight;
  } catch (e) {
    return puts(error("" + 'Can\'t find the docco module.'.red + "\n\nRun cake install to install the dependencies"));
  }

  DoccoFileProcessor = (function() {

    DoccoFileProcessor.TPL_PATH = resolve(__dirname.replace('.cmd', ''), '_page');

    DoccoFileProcessor.asCommand = function(f, h, n) {
      return function(cb) {
        return new DoccoFileProcessor(f, h, n).process(cb);
      };
    };

    function DoccoFileProcessor(file, header, nav) {
      this.file = file;
      this.header = header;
      this.nav = nav;
    }

    DoccoFileProcessor.prototype.highlightFile = function(path, sections, callback) {
      var _this = this;
      return highlight(path, sections, function() {
        var processors, section, _i, _len;
        processors = [];
        for (_i = 0, _len = sections.length; _i < _len; _i++) {
          section = sections[_i];
          processors.push(DoccoPreProcessor.asCommand(path, section));
        }
        return new Parallel(processors).run(function() {
          return callback();
        });
      });
    };

    DoccoFileProcessor.prototype.process = function(callback) {
      var _this = this;
      return fs.readFile(this.file.path, function(err, code) {
        var sections;
        if (err != null) {
          throw err;
        }
        sections = parse(_this.file.path, code.toString());
        return _this.highlightFile(_this.file.path, sections, function() {
          var context;
          context = {
            sections: sections,
            header: _this.header,
            nav: _this.nav
          };
          return render(_this.constructor.TPL_PATH, context, function(err, page) {
            if (err != null) {
              throw err;
            }
            return fs.writeFile(_this.file.outputPath, page, function(err) {
              if (err != null) {
                throw err;
              }
              console.log(("source for " + _this.file.relativePath + "                         documentation processed").squeeze());
              return typeof callback === "function" ? callback() : void 0;
            });
          });
        });
      });
    };

    return DoccoFileProcessor;

  })();

  module.exports = DoccoFileProcessor;

}).call(this);
