// Generated by CoffeeScript 1.3.3
(function() {
  var DoccoFileProcessor;

  DoccoFileProcessor = (function() {

    function DoccoFileProcessor() {}

    return DoccoFileProcessor;

  })();

  module.exports = DoccoFileProcessor;

}).call(this);
