// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(config) {
    config.verbosity = 0;
    config.engines = {
      templates: {},
      databases: {},
      tests: {},
      logging: {}
    };
    return config.defaultLoggingEngine = 'console';
  };

}).call(this);
