// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(config) {
    return config.merge({
      verbosity: 0,
      engines: {
        templates: {},
        databases: {},
        tests: {},
        logging: {}
      },
      tasks: {
        compile: {
          sourceDirectory: 'src',
          compilationDirectory: 'lib'
        }
      },
      defaultLoggingEngine: 'console'
    });
  };

}).call(this);
