// Generated by CoffeeScript 1.3.3
(function() {

  exports.setup = function(config) {
    config.verbose = false;
    return config.engines = {
      templates: {},
      databases: {},
      tests: {}
    };
  };

}).call(this);
