// Generated by CoffeeScript 1.3.3
(function() {
  var print;

  print = require('util').print;

  module.exports = function(config) {
    return config.engines.logging.console = function(logger, log) {
      return print(log.message);
    };
  };

}).call(this);
