// Generated by CoffeeScript 1.3.1
(function() {
  var error, puts, resolve, _ref;

  resolve = require('path').resolve;

  _ref = require('../../../utils/logs'), puts = _ref.puts, error = _ref.error;

  exports.initialize = function(config) {
    return config.engines.templates.hamlc = {
      render: function(tpl, context) {
        var compile, msg;
        try {
          compile = require('haml-coffee').compile;
        } catch (e) {
          msg = "" + (error('Haml-coffee module not found, run neat install.'.red)) + "\n\n" + e.stack;
          return puts(msg);
        }
        return compile(tpl)(context);
      }
    };
  };

}).call(this);
