// Generated by CoffeeScript 1.3.1
(function() {

  exports.initialize = function(config) {
    return config.engines.templates.plain = {
      render: function(tpl, context) {
        return tpl;
      }
    };
  };

}).call(this);
