// Generated by CoffeeScript 1.3.3
(function() {
  var command, describe, fs, namedEntity, usages, _ref;

  fs = require('fs');

  _ref = require('../utils/commands'), describe = _ref.describe, usages = _ref.usages;

  namedEntity = require('../utils/generators').namedEntity;

  usages('neat generate command <name> {description, environment, usages}', describe('Generates a <name> command in the commands directory.\nDescription, usages and environment can be defined with\nthe hash arguments syntax.', command = namedEntity(__filename, 'src/commands', 'cmd.coffee')));

  module.exports = {
    command: command
  };

}).call(this);
