// Generated by CoffeeScript 1.3.3
(function() {
  var Neat, describe, fs, generator, namedEntity, usages, _, _ref;

  fs = require('fs');

  Neat = require('../neat');

  _ref = Neat.require('utils/commands'), describe = _ref.describe, usages = _ref.usages;

  namedEntity = Neat.require('utils/generators').namedEntity;

  _ = Neat.i18n.getHelper();

  usages('neat generate config:packager <name>', describe(_('neat.commands.generate.config_packager.description'), generator = namedEntity(__filename, 'config/packages', 'cup')));

  exports['config:packager'] = generator;

}).call(this);
