// Generated by CoffeeScript 1.3.3
(function() {
  var describe, fs, generator, namedEntity, usages, _ref;

  fs = require('fs');

  _ref = require('../utils/commands'), describe = _ref.describe, usages = _ref.usages;

  namedEntity = require('../utils/generators').namedEntity;

  usages('neat generate generator [name]', describe('Generates a [name] generator in the generators directory', generator = namedEntity(__filename, 'generators', 'gen.coffee')));

  module.exports = {
    generator: generator
  };

}).call(this);
