// Generated by CoffeeScript 1.3.1
(function() {
  var Neat, combine, resolve;

  resolve = require('path').resolve;

  Neat = require('../env').Neat;

  combine = require("../utils/exports").combine;

  module.exports = combine(/\.gen$/, Neat.paths.map(function(p) {
    return "" + p + "/lib/generators";
  }));

}).call(this);
