// Generated by CoffeeScript 1.3.3
(function() {
  var describe, fs, initializer, namedEntity, usages, _ref;

  fs = require('fs');

  _ref = require('../utils/commands'), describe = _ref.describe, usages = _ref.usages;

  namedEntity = require('../utils/generators').namedEntity;

  usages('neat generate initializer <name>', describe('Generates a <name> initializer in the config/initializers directory', initializer = namedEntity(__filename, 'src/config/initializers', 'coffee')));

  module.exports = {
    initializer: initializer
  };

}).call(this);
