// Generated by CoffeeScript 1.3.3
(function() {
  var Neat, describe, namespace, resolve, sample,
    __slice = [].slice;

  resolve = require('path').resolve;

  Neat = require('../neat').Neat;

  namespace = require(resolve(Neat.neatRoot, "lib/utils/exports")).namespace;

  describe = require(resolve(Neat.neatRoot, "lib/utils/commands")).describe;

  describe('A sample generator', sample = function() {
    var args, cb, generator, _i;
    generator = arguments[0], args = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), cb = arguments[_i++];
    console.log(generator);
    console.log(args);
    return typeof cb === "function" ? cb() : void 0;
  });

  module.exports = namespace("sample", {
    index: sample,
    foo: sample,
    bar: sample
  });

}).call(this);
