// Generated by CoffeeScript 1.3.3
(function() {
  var Neat, context, describe, fs, functional, integration, meta, namedEntity, namespace, relative, resolve, unit, usages, _ref, _ref1;

  fs = require('fs');

  _ref = require('path'), relative = _ref.relative, resolve = _ref.resolve;

  Neat = require('../neat');

  _ref1 = Neat.require('utils/commands'), describe = _ref1.describe, usages = _ref1.usages;

  namespace = Neat.require('utils/exports').namespace;

  namedEntity = Neat.require('utils/generators').namedEntity;

  meta = function(name, target) {
    return usages("neat generate spec:" + name + " [name]", describe("Generates a [name] spec in the test/" + name + "s directory", target));
  };

  context = {
    relative: relative,
    testPath: resolve(Neat.root, 'test')
  };

  meta('unit', unit = namedEntity(__filename, 'test/units', 'spec.coffee', context));

  meta('functional', functional = namedEntity(__filename, 'test/functionals', 'spec.coffee', context));

  meta('integration', integration = namedEntity(__filename, 'test/integrations', 'spec.coffee', context));

  module.exports = namespace('spec', {
    unit: unit,
    functional: functional,
    integration: integration
  });

}).call(this);
