// Generated by CoffeeScript 1.3.3
(function() {
  var describe, fs, functional, integration, meta, namedEntity, namespace, unit, usages, _ref;

  fs = require('fs');

  _ref = require('../utils/commands'), describe = _ref.describe, usages = _ref.usages;

  namespace = require('../utils/exports').namespace;

  namedEntity = require('../utils/generators').namedEntity;

  meta = function(name, target) {
    return usages("neat generate spec:" + name + " [name]", describe("Generates a [name] spec in the test/" + name + "s directory", target));
  };

  meta('unit', unit = namedEntity(__filename, 'test/units', 'spec.coffee'));

  meta('functional', functional = namedEntity(__filename, 'test/functionals', 'spec.coffee'));

  meta('integration', integration = namedEntity(__filename, 'test/integrations', 'spec.coffee'));

  module.exports = namespace('spec', {
    unit: unit,
    functional: functional,
    integration: integration
  });

}).call(this);
