// Generated by CoffeeScript 1.3.3
(function() {
  var describe, fs, namedEntity, task, usages, _ref;

  fs = require('fs');

  _ref = require('../utils/commands'), describe = _ref.describe, usages = _ref.usages;

  namedEntity = require('../utils/generators').namedEntity;

  usages('neat generate tasks <name> {description, environment}', describe('Generates a <name> task in the tasks directory.\nDescription and environment of the task can be defined\nusing hash arguments.', task = namedEntity(__filename, 'src/tasks', 'cake.coffee')));

  module.exports = {
    task: task
  };

}).call(this);
