// Generated by CoffeeScript 1.3.3
(function() {
  var describe, fs, namedEntity, task, usages, _ref;

  fs = require('fs');

  _ref = require('../utils/commands'), describe = _ref.describe, usages = _ref.usages;

  namedEntity = require('../utils/generators').namedEntity;

  usages('neat generate tasks [name]', describe('Generates a [name] task in the tasks directory', task = namedEntity(__filename, 'tasks', 'cake.coffee')));

  module.exports = {
    task: task
  };

}).call(this);
