// Generated by CoffeeScript 1.3.1
(function() {
  var Neat, aliases, describe, docco, error, existsSync, findSync, missing, neatBroken, puts, resolve, run, utils, warn, _ref, _ref1, _ref2;

  _ref = require('path'), resolve = _ref.resolve, existsSync = _ref.existsSync;

  Neat = require('../env').Neat;

  utils = resolve(Neat.neatRoot, "lib/utils");

  findSync = require(resolve(utils, "files")).findSync;

  _ref1 = require(resolve(utils, "logs")), puts = _ref1.puts, error = _ref1.error, warn = _ref1.warn, missing = _ref1.missing, neatBroken = _ref1.neatBroken;

  _ref2 = require(resolve(utils, "commands")), run = _ref2.run, aliases = _ref2.aliases, describe = _ref2.describe;

  docco = function(pr) {
    var f;
    if (pr == null) {
      return puts(error("No program provided to docco"));
    }
    return aliases('docco', describe('Generates the documentation for a Neat project through docco', f = function(callback) {
      var doccoPath, files;
      if (Neat.root == null) {
        return puts(error("Can't run neat docco outside of a Neat project."));
      }
      doccoPath = resolve(Neat.neatRoot, 'node_modules/.bin/docco');
      if (!existsSync(doccoPath)) {
        return puts(error("Docco module not found, run neat install."));
      }
      files = findSync('coffee', resolve(Neat.root, 'src/core'));
      files.sort();
      if (files == null) {
        return puts(warn("No source files in the current project"));
      }
      return run(doccoPath, files, callback);
    }));
  };

  module.exports = {
    docco: docco
  };

}).call(this);
