// Generated by CoffeeScript 1.3.3
(function() {
  var Neat, aliases, describe, dummy, error, fs, logger, missing, neatBroken, print, puts, resolve, run, utils, warn, withEnv, _ref, _ref1;

  fs = require('fs');

  resolve = require('path').resolve;

  Neat = require('../neat');

  utils = resolve(Neat.neatRoot, "lib/utils");

  _ref = require(resolve(utils, "logs")), puts = _ref.puts, print = _ref.print, error = _ref.error, warn = _ref.warn, missing = _ref.missing, neatBroken = _ref.neatBroken, logger = _ref.logger;

  _ref1 = require(resolve(utils, "commands")), run = _ref1.run, aliases = _ref1.aliases, describe = _ref1.describe, withEnv = _ref1.withEnv;

  dummy = function(pr) {
    var f;
    if (pr == null) {
      return error("No program provided to dummy");
    }
    return aliases('dummy', describe("I'am a dummy command that print some stuff", withEnv('foo', f = function(cb) {
      print(".".red, 0);
      print(".".yellow, 1);
      print(".".green, 2);
      print(".".cyan, 3);
      print(".".blue, 4);
      puts(".");
      puts("a second line", 1);
      return console.log(logger.stack);
    })));
  };

  module.exports = {
    dummy: dummy
  };

}).call(this);
