// Generated by CoffeeScript 1.3.3
(function() {
  var Neat, aliases, describe, dummy, error, fs, missing, neatBroken, puts, resolve, run, utils, warn, withEnv, _ref, _ref1;

  fs = require('fs');

  resolve = require('path').resolve;

  Neat = require('../neat');

  utils = resolve(Neat.neatRoot, "lib/utils");

  _ref = require(resolve(utils, "logs")), puts = _ref.puts, error = _ref.error, warn = _ref.warn, missing = _ref.missing, neatBroken = _ref.neatBroken;

  _ref1 = require(resolve(utils, "commands")), run = _ref1.run, aliases = _ref1.aliases, describe = _ref1.describe, withEnv = _ref1.withEnv;

  dummy = function(pr) {
    var f;
    if (pr == null) {
      return puts(error("No program provided to dummy"));
    }
    return aliases('dummy', describe('Installs all the dependencies listed in the `Nemfile`', withEnv('foo', f = function(cb) {
      return puts("foooOOO");
    })));
  };

  module.exports = {
    dummy: dummy
  };

}).call(this);
