// Generated by CoffeeScript 1.3.3
(function() {
  var COFFEE, Neat, aliases, describe, error, fs, green, info, install, puts, red, render, resolve, run, utils, _ref, _ref1,
    __slice = [].slice;

  fs = require('fs');

  resolve = require('path').resolve;

  Neat = require('../neat');

  utils = resolve(Neat.neatRoot, "lib/utils");

  COFFEE = "" + Neat.neatRoot + "/node_modules/.bin/coffee";

  _ref = require("../utils/logs"), puts = _ref.puts, error = _ref.error, info = _ref.info, green = _ref.green, red = _ref.red;

  _ref1 = require(resolve(utils, "commands")), run = _ref1.run, aliases = _ref1.aliases, describe = _ref1.describe;

  render = require(resolve(utils, "templates")).render;

  install = function(pr) {
    var f;
    if (pr == null) {
      throw new Error("No program provided to install");
    }
    return aliases('i', 'install', describe('Installs all the dependencies listed in the `Nemfile`', f = function() {
      var args, callback, _i;
      args = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), callback = arguments[_i++];
      if (Neat.root == null) {
        throw new Error("Can't run neat install outside of a Neat project.");
      }
      return fs.readFile('Nemfile', function(err, nemfile) {
        if (err) {
          throw new Error("No " + "Nemfile".red + " in the current directory");
        }
        puts("Nemfile found");
        return render(__filename, function(err, source) {
          if (err != null) {
            throw err;
          }
          source = source.replace("###_NPM_DECLARATION_###", nemfile.toString());
          return run(COFFEE, ['-e', source], function(status) {
            if (status === 0) {
              info(green("Your bundle is complete."));
            } else {
              error(red("An error occured during the installation!"));
            }
            return typeof callback === "function" ? callback() : void 0;
          });
        });
      });
    }));
  };

  module.exports = {
    install: install
  };

}).call(this);
